Starting Debug for lxc0-0
Running Command /home/vignesh/Desktop/awlsim-0.42/tests/run.sh -e 1 --node 0 /home/vignesh/Desktop/awlsim-0.42/tests/modbus/simple_client_server/sfb102_server.awl
6 (process ID) old priority 0, new priority 10
=== Running tests with 'python2'
Running test 'sfb102_server.awl' with 'python2' ... ('Dest IP : ', '10.10.0.10')
('Resolved hostname = ', '10.10.0.10')
('IP of IDS : ', '10.10.0.10')
Traceback (most recent call last):
  File "/home/vignesh/Desktop/awlsim-0.42/tests/../awlsim-cli", line 699, in <module>
    sys.exit(main())
  File "/home/vignesh/Desktop/awlsim-0.42/tests/../awlsim-cli", line 696, in main
    return run(inputFile,node_id,conn_type)
  File "/home/vignesh/Desktop/awlsim-0.42/tests/../awlsim-cli", line 274, in run
    s.startup()
  File "/home/vignesh/Desktop/awlsim-0.42/awlsim/core/main.py", line 163, in startup
    self.cpu.startup()
  File "/home/vignesh/Desktop/awlsim-0.42/awlsim/core/cpu.py", line 873, in startup
    self.__runOB(self.obs[100])
  File "/home/vignesh/Desktop/awlsim-0.42/awlsim/core/cpu.py", line 798, in __runOB
    fd = os.open("/proc/awlsim/vt_time" ,os.O_RDWR)
OSError: [Errno 2] No such file or directory: '/proc/awlsim/vt_time'
=== TEST FAILED ===
Test 'sfb102_server.awl' FAILED
